// <auto-generated />
using System;
using Haceb.Demanda.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Haceb.Demanda.Infrastructure.Migrations
{
    [DbContext(typeof(HacebDbContext))]
    [Migration("20260301223404_InitialDB")]
    partial class InitialDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Haceb.Demanda.Domain.Entities.DemandEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateRegistry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PlaintiffName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Prioritize")
                        .HasColumnType("int");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RatingId");

                    b.HasIndex("TypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Demands", (string)null);
                });

            modelBuilder.Entity("Haceb.Demanda.Domain.Entities.DemandHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("DateRegistry")
                        .HasColumnType("datetime2");

                    b.Property<int>("DemandId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DemandId");

                    b.HasIndex("UserId");

                    b.ToTable("DemandHistories", (string)null);
                });

            modelBuilder.Entity("Haceb.Demanda.Domain.Entities.DemandTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DemandTypes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Proyectos"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Requerimientos"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Soportes"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Incidentes"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Temas legales"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Vulnerabilidades"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Apoyos"
                        });
                });

            modelBuilder.Entity("Haceb.Demanda.Domain.Entities.RatingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Classifications", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Tecnológica"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Legal"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Operativa"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Comercial"
                        });
                });

            modelBuilder.Entity("Haceb.Demanda.Domain.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Role");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "tecnologia@mail.com",
                            IsActive = true,
                            Password = "$2a$11$7QZLqxZsMNMfBVQ.MHgJbepYtK8bfwOvFsFxPhXftPnf.9xx6Kiwm",
                            Role = 1,
                            Username = "Tecnología"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Financiera@mail.com",
                            IsActive = true,
                            Password = "$2a$11$7QZLqxZsMNMfBVQ.MHgJbepYtK8bfwOvFsFxPhXftPnf.9xx6Kiwm",
                            Role = 2,
                            Username = "Financiera"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Negociacion@mail.com",
                            IsActive = true,
                            Password = "$2a$11$7QZLqxZsMNMfBVQ.MHgJbepYtK8bfwOvFsFxPhXftPnf.9xx6Kiwm",
                            Role = 2,
                            Username = "Negociación"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Operaciones@mail.com",
                            IsActive = true,
                            Password = "$2a$11$7QZLqxZsMNMfBVQ.MHgJbepYtK8bfwOvFsFxPhXftPnf.9xx6Kiwm",
                            Role = 2,
                            Username = "Operaciones"
                        },
                        new
                        {
                            Id = 5,
                            Email = "IDI@mail.com",
                            IsActive = true,
                            Password = "$2a$11$7QZLqxZsMNMfBVQ.MHgJbepYtK8bfwOvFsFxPhXftPnf.9xx6Kiwm",
                            Role = 2,
                            Username = "I + D + I"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Comercial@mail.com",
                            IsActive = true,
                            Password = "$2a$11$7QZLqxZsMNMfBVQ.MHgJbepYtK8bfwOvFsFxPhXftPnf.9xx6Kiwm",
                            Role = 2,
                            Username = "Comercial"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Mercadeo@mail.com",
                            IsActive = true,
                            Password = "$2a$11$7QZLqxZsMNMfBVQ.MHgJbepYtK8bfwOvFsFxPhXftPnf.9xx6Kiwm",
                            Role = 2,
                            Username = "Mercadeo"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Talentohumano@mail.com",
                            IsActive = true,
                            Password = "$2a$11$7QZLqxZsMNMfBVQ.MHgJbepYtK8bfwOvFsFxPhXftPnf.9xx6Kiwm",
                            Role = 2,
                            Username = "Talento Humano"
                        });
                });

            modelBuilder.Entity("Haceb.Demanda.Domain.Entities.UserRolEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("UserRols", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ADM",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Code = "USR",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Haceb.Demanda.Domain.Entities.DemandEntity", b =>
                {
                    b.HasOne("Haceb.Demanda.Domain.Entities.RatingEntity", "Rating")
                        .WithMany()
                        .HasForeignKey("RatingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Haceb.Demanda.Domain.Entities.DemandTypeEntity", "TypeEntity")
                        .WithMany("Demands")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Haceb.Demanda.Domain.Entities.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rating");

                    b.Navigation("TypeEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("Haceb.Demanda.Domain.Entities.DemandHistoryEntity", b =>
                {
                    b.HasOne("Haceb.Demanda.Domain.Entities.DemandEntity", "DemandEntity")
                        .WithMany("HistoryEntities")
                        .HasForeignKey("DemandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Haceb.Demanda.Domain.Entities.UserEntity", "UserEntity")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DemandEntity");

                    b.Navigation("UserEntity");
                });

            modelBuilder.Entity("Haceb.Demanda.Domain.Entities.UserEntity", b =>
                {
                    b.HasOne("Haceb.Demanda.Domain.Entities.UserRolEntity", "RoleTrace")
                        .WithMany("UsersTrace")
                        .HasForeignKey("Role")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoleTrace");
                });

            modelBuilder.Entity("Haceb.Demanda.Domain.Entities.DemandEntity", b =>
                {
                    b.Navigation("HistoryEntities");
                });

            modelBuilder.Entity("Haceb.Demanda.Domain.Entities.DemandTypeEntity", b =>
                {
                    b.Navigation("Demands");
                });

            modelBuilder.Entity("Haceb.Demanda.Domain.Entities.UserRolEntity", b =>
                {
                    b.Navigation("UsersTrace");
                });
#pragma warning restore 612, 618
        }
    }
}
